---
- name: stop pocketsoc-ng
  hosts: trainingvms
  become: true
  vars_files:
    - pocketsoc-ng_vars.env

  tasks:
    - name: Install certificates
      shell: docker run --rm --name transfer -v "/etc/letsencrypt:/host-certs" -v "certificates:/container-certs" quay.io/centos/centos:stream8 cp -r /host-certs /container-certs

    - name: Update portainer
      ansible.builtin.git:
        repo: https://www.github.com/drmcrooks/pocketsoc-ng-portainer/
        dest: /opt/pocketsoc-ng-portainer

    - name: portainer docker-compose up
      command: "/usr/local/bin/docker-compose -f /opt/pocketsoc-ng-portainer/docker-compose.yml up -d"


    - name: build portainer admin password
      shell: "{{ admin_password_command }}"
      register: adminpassword

    - name: get portainer admin authkey
      uri:
        url: http://localhost:8081/api/auth
        method: POST
        body: "{ \"username\": \"admin\", \"password\": \"{{ adminpassword.stdout }}\" }"
        body_format: json
        headers:
          Content-Type: "application/json"
      register: auth
        
    - name: start pocketsoc-ng
      ignore_errors: yes
      uri:
        url: "http://localhost:8081/api/stacks/1/start"
        method: POST
        timeout: 600
        body_format: json
        headers:
          Content-Type: "application/json"
          Authorization: "{{ auth.json.jwt  }}"

