---
- name: stop pocketsoc-ng
  hosts: trainingvms
  become: true
  vars_files:
    - pocketsoc-ng_vars.env

  tasks:
    - name: build portainer admin password
      shell: "{{ admin_password_command }}"
      register: adminpassword

    - name: get portainer admin authkey
      uri:
        url: http://localhost/api/auth
        method: POST
        body: "{ \"username\": \"admin\", \"password\": \"{{ adminpassword.stdout }}\" }"
        body_format: json
        headers:
          Content-Type: "application/json"
      register: auth
        
    - name: get stacks
      uri:
        url: "http://localhost/api/stacks"
        method: GET
        body_format: json
        headers:
          Content-Type: "application/json"
          Authorization: "{{ auth.json.jwt  }}"
      register: stacks

    - name: write stacks
      ansible.builtin.debug:
        msg: "{{ stacks }}"
