---
- name: stop pocketsoc-ng
  hosts: trainingvms
  become: true
  vars_files:
    - pocketsoc-ng_vars.env

  tasks:
    - name: check connection
      ansible.builtin.command: /bin/uptime
        
        
    - name: get stacks
      uri:
        url: "http://localhost/api/stacks"
        method: GET
        body_format: json
        headers:
          Content-Type: "application/json"
          Authorization: "{{ auth.json.jwt  }}"
      register: output
